# Generated by Django 5.1.1 on 2024-09-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_shelterlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_capacity', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('available_food', models.BooleanField(default=False)),
                ('available_medical_supplies', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
