# Generated by Django 5.1.1 on 2024-09-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_unverifiedshelter_unique_together_and_more'),
        ('myapp', '0005_shelterresources'),
    ]

    operations = [
    ]
