# Generated by Django 5.1.1 on 2024-09-29 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_20240928_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifiedshelter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unverifiedshelter',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
