# Generated by Django 5.1.1 on 2024-09-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_unverifiedshelter_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unverifiedshelter',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AddField(
            model_name='unverifiedshelter',
            name='water',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='unverifiedshelter',
            name='address',
        ),
    ]
