# Generated by Django 5.1.1 on 2024-09-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_unverifiedshelter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedshelter',
            name='total_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
